<?php

namespace Karudev\AppsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContratController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Karudev\AppsBundle\Controller\ContratController();
        return $instance;
    }
}
