_home:
    pattern:  /
    defaults: { _controller: KarudevSiteBundle:Default:index }

_contact:
    pattern:  /contact
    defaults: { _controller: KarudevSiteBundle:Default:contact }

_profil:
    pattern:  /profil
    defaults: { _controller: KarudevSiteBundle:Default:profil }
 
_disponibilite:
    pattern:  /disponibilite
    defaults: { _controller: KarudevSiteBundle:Default:disponibilite }
    
_apps_enterprise_login:
    pattern:  /enterprise/login
    defaults: { _controller: KarudevAppsBundle:Default:login }

_apps_enterprise_logout:
    pattern:  /enterprise/logout
    defaults: { _controller: KarudevAppsBundle:Default:logout }  
     
_apps_enterprise_login_check:
    pattern:  /enterprise/logincheck
     
_apps_enterprise_contrat:
    pattern:  /enterprise/contrat
    defaults: { _controller: KarudevAppsBundle:Contrat:create }
    
_apps_enterprise_contrat_download:
    pattern:  /enterprise/contrat/download/{id}
    defaults: { _controller: KarudevAppsBundle:Contrat:download }
    
_apps_enterprise_organisation:
    pattern:  /enterprise/organisation
    defaults: { _controller: KarudevAppsBundle:Organisation:create }

_apps_enterprise_contact:
    pattern:  /enterprise/contact
    defaults: { _controller: KarudevAppsBundle:Contact:create }  
    
_apps_enterprise_facture:
    pattern:  /enterprise/facture
    defaults: { _controller: KarudevAppsBundle:Facture:default }  
 
_apps_enterprise_facture_create:
    pattern:  /enterprise/facture/create
    defaults: { _controller: KarudevAppsBundle:Facture:create }  
    
_apps_enterprise_facture_show_all:
    pattern:  /enterprise/facture/show-all
    defaults: { _controller: KarudevAppsBundle:Facture:showall }  

_apps_enterprise_facture_show:
    pattern:  /enterprise/facture/show/{id}
    defaults: { _controller: KarudevAppsBundle:Facture:show }

_apps_enterprise_facture_createdetails:
    pattern:  /enterprise/facture/createdetails/{idFacture}
    defaults: { _controller: KarudevAppsBundle:Facture:createdetails, idFacture:null }
    
_apps_enterprise_facture_download:
    pattern:  /enterprise/facture/download/{id}
    defaults: { _controller: KarudevAppsBundle:Facture:download }    
    
_apps_enterprise_contact_show_all:
    pattern:  /enterprise/contact/show-all
    defaults: { _controller: KarudevAppsBundle:Contact:showall }    

_apps_enterprise_contact_show:
    pattern:  /enterprise/contact/show/{id}
    defaults: { _controller: KarudevAppsBundle:Contact:show } 

_apps_enterprise_contact_edit:
    pattern:  /enterprise/contact/edit/{id}
    defaults: { _controller: KarudevAppsBundle:Contact:edit } 

_apps_enterprise_contact_liercontactorganisation:
    pattern:  /enterprise/contact/liercontactorganisation/{id_contact}
    defaults: { _controller: KarudevAppsBundle:Contact:liercontactorganisation } 


_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
