jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
       Karudev\AppsBundle\Entity\Compte:
           algorithm: sha512
           encode-as-base64: true
           iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
         administrators:
            entity: { class: KarudevAppsBundle:Compte, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/enterprise/login$
            security: false

        secured_area:
            pattern:    ^/enterprise/
            form_login:
                check_path: /enterprise/logincheck
                login_path: /enterprise/login
                default_target_path: /enterprise/contrat
            logout:
                path:   /enterprise/logout
                target: /enterprise/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/enterprise/contrat, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
