<?php

namespace Karudev\AppsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
     public function get($idOwner) {
        $dql = "SELECT f
					FROM KarudevAppsBundle:Facture f
					
                                        where f.id_owner = ".$idOwner."";

        //die($dql);
        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->getResult();
    }
}
