<?php

namespace Karudev\AppsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiencontactorganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiencontactorganisationRepository extends EntityRepository
{
     public function get($idContact) {
        $dql = "SELECT l,o
					FROM KarudevAppsBundle:Liencontactorganisation l
					inner join l.id_organisation o
                                        where l.id_contact = ".$idContact."";

        //die($dql);
        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->getResult();
    }
}
