<?php

namespace Karudev\AppsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MethodPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MethodPaymentRepository extends EntityRepository
{
}
