<?php

namespace Karudev\AppsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiencontactorganisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganisationRepository extends EntityRepository {

   

}
