<?php

namespace Proxies\__CG__\Karudev\AppsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contrat extends \Karudev\AppsBundle\Entity\Contrat implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTypeContrat($typeContrat)
    {
        $this->__load();
        return parent::setTypeContrat($typeContrat);
    }

    public function getTypeContrat()
    {
        $this->__load();
        return parent::getTypeContrat();
    }

    public function setDuree($duree)
    {
        $this->__load();
        return parent::setDuree($duree);
    }

    public function getDuree()
    {
        $this->__load();
        return parent::getDuree();
    }

    public function setLieu($lieu)
    {
        $this->__load();
        return parent::setLieu($lieu);
    }

    public function getLieu()
    {
        $this->__load();
        return parent::getLieu();
    }

    public function setHoraires($horaires)
    {
        $this->__load();
        return parent::setHoraires($horaires);
    }

    public function getHoraires()
    {
        $this->__load();
        return parent::getHoraires();
    }

    public function setDelaiExecution($delaiExecution)
    {
        $this->__load();
        return parent::setDelaiExecution($delaiExecution);
    }

    public function getDelaiExecution()
    {
        $this->__load();
        return parent::getDelaiExecution();
    }

    public function setMoyensFournis($moyensFournis)
    {
        $this->__load();
        return parent::setMoyensFournis($moyensFournis);
    }

    public function getMoyensFournis()
    {
        $this->__load();
        return parent::getMoyensFournis();
    }

    public function setPeriodiciteReunions($periodiciteReunions)
    {
        $this->__load();
        return parent::setPeriodiciteReunions($periodiciteReunions);
    }

    public function getPeriodiciteReunions()
    {
        $this->__load();
        return parent::getPeriodiciteReunions();
    }

    public function setPrixHt($prixHt)
    {
        $this->__load();
        return parent::setPrixHt($prixHt);
    }

    public function getPrixHt()
    {
        $this->__load();
        return parent::getPrixHt();
    }

    public function setFrais($frais)
    {
        $this->__load();
        return parent::setFrais($frais);
    }

    public function getFrais()
    {
        $this->__load();
        return parent::getFrais();
    }

    public function setMontantAccompte($montantAccompte)
    {
        $this->__load();
        return parent::setMontantAccompte($montantAccompte);
    }

    public function getMontantAccompte()
    {
        $this->__load();
        return parent::getMontantAccompte();
    }

    public function setUnitePrix($unitePrix)
    {
        $this->__load();
        return parent::setUnitePrix($unitePrix);
    }

    public function getUnitePrix()
    {
        $this->__load();
        return parent::getUnitePrix();
    }

    public function setIdOrganisation(\Karudev\AppsBundle\Entity\Organisation $idOrganisation = NULL)
    {
        $this->__load();
        return parent::setIdOrganisation($idOrganisation);
    }

    public function getIdOrganisation()
    {
        $this->__load();
        return parent::getIdOrganisation();
    }

    public function setIdResponsableClient(\Karudev\AppsBundle\Entity\Contact $idResponsableClient = NULL)
    {
        $this->__load();
        return parent::setIdResponsableClient($idResponsableClient);
    }

    public function getIdResponsableClient()
    {
        $this->__load();
        return parent::getIdResponsableClient();
    }

    public function setDateDebut($dateDebut)
    {
        $this->__load();
        return parent::setDateDebut($dateDebut);
    }

    public function getDateDebut()
    {
        $this->__load();
        return parent::getDateDebut();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIdOwner($idOwner)
    {
        $this->__load();
        return parent::setIdOwner($idOwner);
    }

    public function getIdOwner()
    {
        $this->__load();
        return parent::getIdOwner();
    }

    public function setIdModified($idModified)
    {
        $this->__load();
        return parent::setIdModified($idModified);
    }

    public function getIdModified()
    {
        $this->__load();
        return parent::getIdModified();
    }

    public function setIdFreelance(\Karudev\AppsBundle\Entity\Compte $idFreelance = NULL)
    {
        $this->__load();
        return parent::setIdFreelance($idFreelance);
    }

    public function getIdFreelance()
    {
        $this->__load();
        return parent::getIdFreelance();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'type_contrat', 'duree', 'lieu', 'horaires', 'delai_execution', 'moyens_fournis', 'periodicite_reunions', 'prix_ht', 'frais', 'montant_accompte', 'unite_prix', 'date_debut', 'date_created', 'date_last_modified', 'id_owner', 'id_modified', 'id_freelance', 'id_organisation', 'id_responsable_client');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}