<?php

namespace Proxies\__CG__\Karudev\AppsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Organisation extends \Karudev\AppsBundle\Entity\Organisation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdOrganisation()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idOrganisation"];
        }
        $this->__load();
        return parent::getIdOrganisation();
    }

    public function setIdOwner($idOwner)
    {
        $this->__load();
        return parent::setIdOwner($idOwner);
    }

    public function getIdOwner()
    {
        $this->__load();
        return parent::getIdOwner();
    }

    public function setDateCreation($dateCreation)
    {
        $this->__load();
        return parent::setDateCreation($dateCreation);
    }

    public function getDateCreation()
    {
        $this->__load();
        return parent::getDateCreation();
    }

    public function setIdModifier($idModifier)
    {
        $this->__load();
        return parent::setIdModifier($idModifier);
    }

    public function getIdModifier()
    {
        $this->__load();
        return parent::getIdModifier();
    }

    public function setIdDirecteur($idDirecteur)
    {
        $this->__load();
        return parent::setIdDirecteur($idDirecteur);
    }

    public function getIdDirecteur()
    {
        $this->__load();
        return parent::getIdDirecteur();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setAdresseLigne1($adresseLigne1)
    {
        $this->__load();
        return parent::setAdresseLigne1($adresseLigne1);
    }

    public function getAdresseLigne1()
    {
        $this->__load();
        return parent::getAdresseLigne1();
    }

    public function setAdresseLigne2($adresseLigne2)
    {
        $this->__load();
        return parent::setAdresseLigne2($adresseLigne2);
    }

    public function getAdresseLigne2()
    {
        $this->__load();
        return parent::getAdresseLigne2();
    }

    public function setAdresseLigne3($adresseLigne3)
    {
        $this->__load();
        return parent::setAdresseLigne3($adresseLigne3);
    }

    public function getAdresseLigne3()
    {
        $this->__load();
        return parent::getAdresseLigne3();
    }

    public function setCp($cp)
    {
        $this->__load();
        return parent::setCp($cp);
    }

    public function getCp()
    {
        $this->__load();
        return parent::getCp();
    }

    public function setVille($ville)
    {
        $this->__load();
        return parent::setVille($ville);
    }

    public function getVille()
    {
        $this->__load();
        return parent::getVille();
    }

    public function setRegion($region)
    {
        $this->__load();
        return parent::setRegion($region);
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }

    public function setPays($pays)
    {
        $this->__load();
        return parent::setPays($pays);
    }

    public function getPays()
    {
        $this->__load();
        return parent::getPays();
    }

    public function setTel($tel)
    {
        $this->__load();
        return parent::setTel($tel);
    }

    public function getTel()
    {
        $this->__load();
        return parent::getTel();
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setSiteWeb($siteWeb)
    {
        $this->__load();
        return parent::setSiteWeb($siteWeb);
    }

    public function getSiteWeb()
    {
        $this->__load();
        return parent::getSiteWeb();
    }

    public function setIdSecteurActivite($idSecteurActivite)
    {
        $this->__load();
        return parent::setIdSecteurActivite($idSecteurActivite);
    }

    public function getIdSecteurActivite()
    {
        $this->__load();
        return parent::getIdSecteurActivite();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setSiret($siret)
    {
        $this->__load();
        return parent::setSiret($siret);
    }

    public function getSiret()
    {
        $this->__load();
        return parent::getSiret();
    }

    public function setCapital($capital)
    {
        $this->__load();
        return parent::setCapital($capital);
    }

    public function getCapital()
    {
        $this->__load();
        return parent::getCapital();
    }

    public function setStatutJuridique($statutJuridique)
    {
        $this->__load();
        return parent::setStatutJuridique($statutJuridique);
    }

    public function getStatutJuridique()
    {
        $this->__load();
        return parent::getStatutJuridique();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idOrganisation', 'idOwner', 'dateCreation', 'idModifier', 'idDirecteur', 'dateLastModified', 'nom', 'adresseLigne1', 'adresseLigne2', 'adresseLigne3', 'cp', 'ville', 'region', 'pays', 'tel', 'fax', 'email', 'siteWeb', 'siret', 'capital', 'statut_juridique', 'idSecteurActivite', 'description');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}